"""updated nutrients table

Revision ID: d2682e013c03
Revises: 9c18d60bf16c
Create Date: 2023-12-09 13:33:41.449628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2682e013c03'
down_revision = '9c18d60bf16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NutrientGroup', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrients', schema=None) as batch_op:
        batch_op.drop_column('NutrientGroup')

    # ### end Alembic commands ###
