"""update food categories again

Revision ID: f1f787ddf2eb
Revises: c01bc8211376
Create Date: 2023-12-09 16:33:47.517395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f787ddf2eb'
down_revision = 'c01bc8211376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_categories', schema=None) as batch_op:
        batch_op.alter_column('FoodCategoryName',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_categories', schema=None) as batch_op:
        batch_op.alter_column('FoodCategoryName',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
