"""added food name search vector

Revision ID: f84d30ec350c
Revises: f1f787ddf2eb
Create Date: 2023-12-11 10:55:15.762550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types import TSVectorType

# revision identifiers, used by Alembic.
revision = 'f84d30ec350c'
down_revision = 'f1f787ddf2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FoodNameSearchVector', TSVectorType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_column('FoodNameSearchVector')

    # ### end Alembic commands ###
